  CREATE TABLE "ROLE"
   (
        "ROLE" VARCHAR2(20 BYTE),
        PRIMARY KEY ("ROLE")
   );

INSERT INTO "ROLE" values ('ADMIN');
INSERT INTO "ROLE" values ('USER');

  CREATE SEQUENCE  "S_USERS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 100 CACHE 100 NOORDER  NOCYCLE ;
  CREATE TABLE "USERS"
   (	"ID" NUMBER(19,0),
	"NAME" VARCHAR2(255 BYTE) NOT NULL,
	"PASSWORD" VARCHAR2(255 BYTE),
	"EMAIL" VARCHAR2(255 BYTE) NOT NULL,
      CONSTRAINT PK_USERS PRIMARY KEY ("ID"),
      CONSTRAINT "UK_PLAYER_NAME" UNIQUE ("NAME")
   ) ;

  CREATE TABLE "USERROLE"
   (	"USERID" NUMBER(19,0),
	"ROLE" VARCHAR2(20 BYTE),
      CONSTRAINT "PK_USERROLE" PRIMARY KEY ("USERID", "ROLE"),
      CONSTRAINT "FK_USERROLE_PLAYER" FOREIGN KEY ("USERID") REFERENCES "USERS" ("ID") ON DELETE CASCADE,
      CONSTRAINT "FK_USERROLE_ROLE" FOREIGN KEY ("ROLE") REFERENCES "ROLE" ("ROLE")
   ) ;

  CREATE SEQUENCE  "S_DEVICECONFIG"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 100 CACHE 100 NOORDER  NOCYCLE ;
  CREATE TABLE "DEVICECONFIG"
   (	"ID" NUMBER(19,0),
	"CODE" VARCHAR2(20 BYTE) NOT NULL,
	"NAME" VARCHAR2(255 BYTE),
        "DEVICETYPE" VARCHAR2(20 BYTE) NOT NULL,
        "SNMPDESCRIPTOR" CLOB NOT NULL,
        "ACTIVE" NUMBER(1,0) NOT NULL,
      CONSTRAINT "PK_DEVICECONFIG" PRIMARY KEY ("ID"),
      CONSTRAINT "UK_DEVICECONFIG_CODE" UNIQUE ("CODE")
   ) ;

  CREATE SEQUENCE  "S_DEVICE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 100 CACHE 100 NOORDER  NOCYCLE ;
  CREATE TABLE "DEVICE"
   (	"ID" NUMBER(19,0),
	"IPADDRESS" VARCHAR2(20 BYTE) NOT NULL,
	"MACADDRESS" VARCHAR2(20 BYTE),
	"NODEID" VARCHAR2(20 BYTE),
	"CONFIGID" NUMBER(19, 0),
      CONSTRAINT "PK_DEVICE" PRIMARY KEY ("ID"),
      CONSTRAINT "UK_DEVICE_IPADDRESS" UNIQUE ("IPADDRESS"),
      CONSTRAINT "FK_DEVICE_DEVICECONFIG" FOREIGN KEY ("CONFIGID") REFERENCES "DEVICECONFIG" ("ID")
   ) ;

    
  CREATE SEQUENCE  "S_HISTORY"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 100 CACHE 100 NOORDER  NOCYCLE ;
  CREATE TABLE "HISTORY"
   (	"ID" NUMBER(19,0),
        "DEVICEID" NUMBER(19, 0) NOT NULL,
        "OLDCONFIGID" NUMBER(19, 0),
        "NEWCONFIGID" NUMBER(19, 0),
        "USERNAME" VARCHAR2(255 BYTE) NOT NULL,
        "DESCRIPTION" VARCHAR2(255 BYTE) NOT NULL,
        "UPDATETIME" TIMESTAMP (6) NOT NULL,
      CONSTRAINT PK_CHANGELOG PRIMARY KEY ("ID"),
      CONSTRAINT "FK_CHANGELOG_OLDCONFIGID" FOREIGN KEY ("OLDCONFIGID") REFERENCES "DEVICECONFIG" ("ID"),
      CONSTRAINT "FK_CHANGELOG_NEWCONFIGID" FOREIGN KEY ("NEWCONFIGID") REFERENCES "DEVICECONFIG" ("ID"),
      CONSTRAINT "FK_CHANGELOG_USERID" FOREIGN KEY ("USERID") REFERENCES "USERS" ("ID"),
      CONSTRAINT "FK_CHANGELOG_DEVICEID" FOREIGN KEY ("DEVICEID") REFERENCES "DEVICE" ("ID")
   ) ;

