  CREATE TABLE "ROLE"
   (
        "ROLE" VARCHAR2(20 BYTE),
        PRIMARY KEY ("ROLE")
   );

INSERT INTO "ROLE" values ('ADMIN');
INSERT INTO "ROLE" values ('USER');

  CREATE SEQUENCE  "S_USERS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 100 CACHE 100 NOORDER  NOCYCLE ;
  CREATE TABLE "USERS"
   (	"ID" NUMBER(19,0),
	"NAME" VARCHAR2(255 BYTE) NOT NULL,
	"PASSWORD" VARCHAR2(255 BYTE),
	"EMAIL" VARCHAR2(255 BYTE) NOT NULL,
      CONSTRAINT PK_USERS PRIMARY KEY ("ID"),
      CONSTRAINT "UK_PLAYER_NAME" UNIQUE ("NAME")
   ) ;

  CREATE TABLE "USERROLE"
   (	"USERID" NUMBER(19,0),
	"ROLE" VARCHAR2(20 BYTE),
      CONSTRAINT "PK_USERROLE" PRIMARY KEY ("USERID", "ROLE"),
      CONSTRAINT "FK_USERROLE_PLAYER" FOREIGN KEY ("USERID") REFERENCES "USERS" ("ID") ON DELETE CASCADE,
      CONSTRAINT "FK_USERROLE_ROLE" FOREIGN KEY ("ROLE") REFERENCES "ROLE" ("ROLE")
   ) ;

  CREATE SEQUENCE  "S_SNMPTYPE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 100 CACHE 100 NOORDER  NOCYCLE ;
  CREATE TABLE "SNMPTYPE"
   (	"ID" NUMBER(19,0),
	"CODE" VARCHAR2(20 BYTE) NOT NULL,
	"NAME" VARCHAR2(255 BYTE) NOT NULL,
        "SNMPDESCRIPTOR" CLOB NOT NULL,
        "ACTIVE" NUMBER(1,0),
      CONSTRAINT "PK_GAMECONTEXT" PRIMARY KEY ("ID"),
      CONSTRAINT "UK_SNMPTYPE_CODE" UNIQUE ("CODE")
   ) ;

  CREATE SEQUENCE  "S_CLIENT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 100 CACHE 100 NOORDER  NOCYCLE ;
  CREATE TABLE "CLIENT"
   (	"ID" NUMBER(19,0),
	"IPADDRESS" VARCHAR2(20 BYTE) NOT NULL,
	"TYPEID" NUMBER(19, 0),
      CONSTRAINT "PK_CLIENT" PRIMARY KEY ("ID"),
      CONSTRAINT "UK_CLIENT_IPADDRESS" UNIQUE ("IPADDRESS"),
      CONSTRAINT "FK_CLIENT_SNMPTYPE" FOREIGN KEY ("TYPEID") REFERENCES "SNMPTYPE" ("ID")
   ) ;

    
  CREATE SEQUENCE  "S_HISTORY"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 100 CACHE 100 NOORDER  NOCYCLE ;
  CREATE TABLE "HISTORY"
   (	"ID" NUMBER(19,0),
        "CLIENTID" NUMBER(19, 0) NOT NULL,
        "OLDTYPEID" NUMBER(19, 0),
        "NEWTYPEID" NUMBER(19, 0),
        "USERID" NUMBER(19, 0),
        "UPDATETIME" TIMESTAMP (6) NOT NULL,
      CONSTRAINT PK_CHANGELOG PRIMARY KEY ("ID"),
      CONSTRAINT "FK_CHANGELOG_OLDTYPEID" FOREIGN KEY ("OLDTYPEID") REFERENCES "SNMPTYPE" ("ID"),
      CONSTRAINT "FK_CHANGELOG_NEWTYPEID" FOREIGN KEY ("NEWTYPEID") REFERENCES "SNMPTYPE" ("ID"),
      CONSTRAINT "FK_CHANGELOG_USERID" FOREIGN KEY ("USERID") REFERENCES "USERS" ("ID"),
      CONSTRAINT "FK_CHANGELOG_CLIENTID" FOREIGN KEY ("CLIENTID") REFERENCES "CLIENT" ("ID")
   ) ;

